### ISSUE TITLE
"misc" refs don't get DOI printed on the PDF

### ISSUE THREAD

**Issue by ThomasLecocq** [WeAreSeismica/submission-template#6]
I was checking DOIs of _misc_ type bib entries and noticed they don't make it to the final compiled PDF. I guess it has to do with natbib ?
![image](https://user-images.githubusercontent.com/916937/187360760-1bfc7f73-6869-4149-99c4-ba7f9bd1d5ec.png)

**Comment by thearagon** [comment]
Actually it's the bibliographic style we use (abbrvnat), there is no doi field in the misc type. I actually never used misc types, is there a specific reason to choose this one over article in your case?
I could update the misc type in our style, but I am not sure I want to do it, because it seems that misc refs shouldn't be doi-ed by design. Any thoughts?

**Comment by ThomasLecocq** [comment]
Thanks for the expanation. the "misc" choice isn't mine, so I guess we can change it safely. It'll be important to check for tex submissions that authors haven't also mistakenly used it (if there is a DOI to be shown).
